import IOTATransaction

From = 'HGW9HB9LJPYUGVHNGCPLFKKPNZAIIFHZBDHKSGMQKFMANUBASSMSV9TAJSSMPRZZU9SFZULXKJ9YLAIUA'
To = 'BXOM9LUNLPSEXBRJV9UUNLHSUHABEOGHQOGNBNBUEYSGOFZOEPYKEYRSFTXBOEJLUODUQXXGQ9NWQBSGH'


a = IOTATransaction.IOTATransaction(From)
#pt = a.MakePreparingTransaction(To,'Hello, I am Kevin.')
#a.SendTransaction([pt])
#print(a.GetTransactionHash())

print(a.GetTransactionMessage('AYKWRKTOC9SPPWHNWJPWXC9QTB9BCYUMH9FJLIIPKXAWMKFQFBNDPFKYIOHXRJQGUALNGUUIGPPR99999'))
